### ISSUE TITLE
[FEATURE] Add support for PartiQL in the V2 engine

### ISSUE THREAD

**Issue by GumpacG** [opensearch-project/sql#1104]
**Is your feature request related to a problem?**
Running doctests on the v2 engine without falling back to the legacy engine fails on `partiql.rst`.
Query: `SELECT city, accounts, projects FROM people;`

Error: 
`Failed example:
    sql_cmd.process('SELECT city, accounts, projects FROM people')Exception raised:
    Traceback (most recent call last):
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest partiql.rst[0]>", line 1, in <module>
        sql_cmd.process('SELECT city, accounts, projects FROM people')
      File "/Users/guiang/Documents/GitHub/opensearch-project-sql/doctest/test_docs.py", line 42, in process
        output = self.formatter.format_output(data)
      File "/Users/guiang/Documents/GitHub/opensearch-project-sql/sql-cli/src/opensearch_sql_cli/formatter.py", line 60, in format_output
        datarows = data["datarows"]
    TypeError: 'NoneType' object is not subscriptable`

**Comment by dai-chen** [comment]
# PartiQL Support in OpenSearch SQL V2 Engine

## Background

Previously we identified 6 common usage in PartiQL and added limited support in legacy engine:

* P0: Enable access to nested attributes with optional UNNEST keyword
* P1: Enable access to nested attributes with LEFT JOIN
* P2: Support full-text search and rank by similarity score
* P2: Support Grouping by Elasticsearch Aggregation
* P2: Check whether a nested collection satisfies a condition
* P2: Support subqueries that aggregate over nested collections

## Proposed Solution

The key challenge is in the design of logical and physical operator behind PartiQL grammar. Take the following query for example in this section:

```
SELECT e.name, p.name
FROM employees AS e,
     e.projects AS p
WHERE p.name LIKE '%security%'
```

### Approach 1: Adding New Operator for Unnest Operation

First option is to add a new UNNEST operator to handle the comma join in FROM clause entirely.

```
Project(Q(e.name, STRING), Q(p.name, STRING))
- Filter(Like(Q(p.name, STRING), '%security%'))
 - Unnest(Q(e.projects, ARRAY), p)
  - OpenSearchIndexScan(employees, e)
```

* Pros
    * Very straightforward to understand and implement
* Cons
    * Difficult to deduce the semantics for deep nested query
    * Need to implement each correlate operation defined in PartiQL for this new operator, ex. CROSS, INNER, OUTER, SEMI

### Approach 2: Reusing Nested Loop Join Operator *[Preferred]*

Alternatively, we can reuse nested loop operator.

```
Project(Q(e.name, STRING), Q(p.name, STRING))
- Filter(Like(Q(p.name, STRING), '%security%'))
 - NestedLoop(type=inner, on=Eq(e._id, ) -- Virtual id to join parent and inner doc
  - OpenSearchIndexScan(employees, e)
  - NestedScan(e.projects, p) -- Special scan whose input comes from left side scan operator
```

* Pros
    * Reuse same operators as JOIN
    * Deep nested field is supported by multi-join automatically
* Cons
    * Need to do some "trick" so right side can access each row generated by left side

This is how SQL Lateral Join implemented and inspired by a sentence in PartiQL spec 5.7 SQL's LATERAL. Find more details in appendix.

> SQL 2003 used the LATERAL keyword to correlate FROM clause items. In the interest of compatibility with SQL, PartiQL
also allows the use of the keyword LATERAL, though it does not do anything more than the comma itself would do.
That is “l , LATERAL r” is equivalent to “l , r”.

## Examples

### E1: Enable access to nested attributes with optional UNNEST keyword

Query:

```
SELECT e.name, p.name
FROM employees AS e,
     e.projects AS p
WHERE p.name LIKE '%security%'
```

# WIP...


## Physical Operator Implementation

Generic nested loop operator. `LateralContract` interface allows right side to fetch row from left side. <-- Need more investigation how to make this support generic lateral join

```
class NestedLoop implements PhysicalOperator, LateralContract:
  val left : PhysicalOperator
  val right : PhysicalOperator
  val joinCond: Expression
  var lnext: ExprValue
 
  def hasNext(): boolean = {
    return next != null
  }
 
  def loadNext() = {
    for lnext in left.next():  // lnext is set here
      for rnext in right.next():
        joinCond.valueOf({lnext, rnext}) is True:
          next = output(lnext, rnext)
  }

  def getLeftOutput():
    return lnext

class LateralScan implements PhysicalOperator:
 val lateral: LateralContract
 val ref: Reference  // nested field name
 val next: ExprValue

 def hasNext(): boolean = {
   return next != null
 }
 
 def next(): ExprValue = {
   next = ref.valueOf(lateral.getLeftOutput())
   return next
 }
```

* * *
## Appendix

Here explains what's lateral join and you will see how similar it is as PartiQL in the case of nested JSON value:

>A `LATERAL` join is more like a [correlated subquery](https://en.wikipedia.org/wiki/Correlated_subquery), not a plain subquery, in that ***expressions to the right of a lateral join are evaluated once for each row left of it*** - just like a correlated subquery - while a plain subquery (table expression) is evaluated *once* only. The difference between Lateral Join and Correlated Subquery is: There are things that a lateral join can do, but a (correlated) subquery cannot (easily). A correlated subquery can only return a single value, not multiple columns and not multiple rows.

For example in PostgreSQL 9.6: At execution time, variable `p` is binding to each row of table test. The right side of join has access to it and flatten `p.data` to left join each nested row bind to variable `child` with their parent row bind to `p` currently.

```
CREATE TABLE test(id SERIAL PRIMARY KEY, data JSONB);

INSERT INTO test(data) VALUES
   ('{"parent":null,"children":[2,3]}'),
   ('{"parent":1,   "children":[4,5]}'),
   ('{"parent":1,   "children":[]}'),
   ('{"parent":2,   "children":[]}'),
   ('{"parent":2,   "children":[]}');

SELECT p.data, child
FROM   test p
LEFT JOIN LATERAL jsonb_array_elements_text(p.data->'children') child
ON TRUE;
```

Results:
<img width="1018" alt="Screen Shot 2022-12-30 at 11 18 07 AM" src="https://user-images.githubusercontent.com/46505291/217396304-2d516c5f-782f-4e26-94d4-384cebe5122c.png">

Query execution plan:
<img width="1168" alt="Screen Shot 2022-12-30 at 11 18 57 AM" src="https://user-images.githubusercontent.com/46505291/217396496-eace505e-aa44-49bb-803c-9de1d40c4b26.png">

**Comment by dai-chen** [comment]
@MaxKsyunz Thanks for your early review! Will let you know when I'm done today. Let me see if I can answer this in Examples section. Afterwards, I will link this to our Nested Function PR for more discussion. Thanks!

**Comment by LantaoJin** [comment]
Won't do as v2 only.
