### ISSUE TITLE
[BUG] PPL integration test fails in Turkish locale

### ISSUE THREAD

**Issue by seankao-az** [opensearch-project/sql#1590]
**What is the bug?**
`StandaloneIT.testSourceFieldQuery` fails in `tr-TR` locale.

**How can one reproduce the bug?**
1. check out to commit 3fc11a40945c1dbe8aa6096a829d0e09ee5c0f3d
2. run `./gradlew ':integ-test:integTest' --tests "org.opensearch.sql.ppl.StandaloneIT.testSourceFieldQuery" -Dtests.seed=2E353120D2BDBBBB -Dtests.security.manager=false -Dtests.locale=tr-TR -Dtests.timezone=Africa/Gaborone -Druntime.java=17`

Also reproducible on 30ac27622b4ca1e3b54463cd6254e78b7bef1642 (2.x branch). Might have existed for a while

**What is the expected behavior?**
All integration tests pass

**What is your host/environment?**
Discovered on Github Actions, reproduced on Intel MacBook pro

**Do you have any screenshots?**

**Do you have any additional context?**
<details><summary>Logs</summary>
<p>

```
REPRODUCE WITH: ./gradlew ':integ-test:integTest' --tests "org.opensearch.sql.ppl.StandaloneIT.testSourceFieldQuery" -Dtests.seed=2E353120D2BDBBBB -Dtests.security.manager=false -Dtests.locale=tr-TR -Dtests.timezone=Africa/Gaborone -Druntime.java=17
org.opensearch.sql.ppl.StandaloneIT > testSourceFieldQuery FAILED
    org.junit.ComparisonFailure: expected:<...,
          "type": "str[i]ng"
        }
      ],
      "da...> but was:<...,
          "type": "str[ı]ng"
        }
      ],
      "da...>
        at __randomizedtesting.SeedInfo.seed([2E353120D2BDBBBB:B4B7B9A7D1BE37B5]:0)
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.opensearch.sql.ppl.StandaloneIT.testSourceFieldQuery(StandaloneIT.java:105)
``` 

</p>
</details>

**Comment by Yury-Fridlyand** [comment]
Similar to #1275
