### ISSUE TITLE
[BUG] Error handling datasources on cluster startup

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/sql#1654]
**What is the bug?**
Error in IT cluster logs:
```
java.lang.IllegalArgumentException: DataSource with name: delete_prometheus doesn't exist.
```
Full exception stack:
```
[2023-05-23T10:43:15,649][ERROR][o.o.s.d.r.RestDataSourceQueryAction] [integTest-0] Error happened during request handling
java.lang.IllegalArgumentException: DataSource with name: delete_prometheus doesn't exist.
	at org.opensearch.sql.datasources.service.DataSourceServiceImpl.getDataSourceMetadata(DataSourceServiceImpl.java:73) ~[datasources-3.0.0.0-SNAPSHOT.jar:?]
	at org.opensearch.sql.datasources.transport.TransportGetDataSourceAction.handleSingleDataSourceRequest(TransportGetDataSourceAction.java:85) ~[datasources-3.0.0.0-SNAPSHOT.jar:?]
	at org.opensearch.sql.datasources.transport.TransportGetDataSourceAction.doExecute(TransportGetDataSourceAction.java:59) [datasources-3.0.0.0-SNAPSHOT.jar:?]
	at org.opensearch.sql.datasources.transport.TransportGetDataSourceAction.doExecute(TransportGetDataSourceAction.java:25) [datasources-3.0.0.0-SNAPSHOT.jar:?]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:218) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:188) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:107) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:472) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.sql.datasources.rest.RestDataSourceQueryAction.lambda$executeGetRequest$3(RestDataSourceQueryAction.java:161) [datasources-3.0.0.0-SNAPSHOT.jar:?]
	at org.opensearch.sql.datasources.utils.Scheduler.lambda$withCurrentContext$0(Scheduler.java:30) [datasources-3.0.0.0-SNAPSHOT.jar:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**How can one reproduce the bug?**
1. Run IT
2. Read cluster logs

**What is the expected behavior?**
No error should be there

**What is your host/environment?**
8e5d766 @ `main`

**Comment by Yury-Fridlyand** [comment]
CI Logs: [test-reports-ubuntu-latest-11 (1).zip](https://github.com/opensearch-project/sql/files/11557354/test-reports-ubuntu-latest-11.1.zip)

**Comment by qianheng-aws** [comment]
Parking: Low activity and deprioritized during triage. Labeled `triage/parked` for tracking. Reopen if needed.
