### ISSUE TITLE
[BUG] Zone_rules_exception “Unknown time-zone ID: Browser” on Kibana

### ISSUE THREAD

**Issue by GezimSejdiu** [opensearch-project/sql#18]
Hi team,
 
we did experience a strange behavior of Kibana when upgrading it to the latest version of ODFE 1.13.2.
**Describe the bug**
> Zone_rules_exception “Unknown time-zone ID: Browser”

This doesn't happen when using Browser as a default time zone but rather when changing it to e.g. "UTC" and upgrading the ODFE version. It may be related to the cache and it gets resolved by doing "force refresh" e.g. on Chome via Ctrl + R. I just wanted to report it in case the ODFE team wants to debug a bit further on the issue. 

Here is the error user gets on Kibana: 
```
zone_rules_exception
Unknown time-zone ID: Browser
Error: Bad Request
    at Fetch._callee3$ (https://<host>/36136/bundles/core/core.entry.js:6:59535)
    at tryCatch (https://<host>/36136/bundles/plugin/opendistroQueryWorkbenchKibana/opendistroQueryWorkbenchKibana.plugin.js:1:32004)
    at Generator.invoke [as _invoke] (https://<host>/36136/bundles/plugin/opendistroQueryWorkbenchKibana/opendistroQueryWorkbenchKibana.plugin.js:1:35968)
    at Generator.forEach.prototype.<computed> [as next] (https://<host>/36136/bundles/plugin/opendistroQueryWorkbenchKibana/opendistroQueryWorkbenchKibana.plugin.js:1:33129)
    at fetch_asyncGeneratorStep (https://<host>/36136/bundles/core/core.entry.js:6:52652)
    at _next (https://<host>/36136/bundles/core/core.entry.js:6:52968)
```
and it seems to be coming mostly from `opendistroQueryWorkbenchKibana`.

**To Reproduce**
- Install the previous version of ODFE using [Debian Package](https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/).
- Set time-zone to UTC on *Stack Managment* --> Advanced Settings -- Kibana
- Upgrade it to the latest via [Rolling Upgrade](https://opendistro.github.io/for-elasticsearch-docs/docs/upgrade/rolling/).
- Upgrade Kibana as well : 
  ```
  sudo apt install -y opendistroforelasticsearch-kibana
  sudo /bin/systemctl start kibana.service
  ```
After these steps are done, open Kibana URL, and you will see an Error message (as above) complaining that `Zone_rules_exception “Unknown time-zone ID: Browser”`

**Expected behavior**
Should be able to pick up the time-zone setup in Kibana.

**Plugins**
Default pluginns shiped with ODFE.

**Host/Environment (please complete the following information):**
 - OS: ubuntu
 - Version 1804-bionic

**Comment by int-rnd** [comment]
This may not be time zone. I had pretty much the same error when doing any search. Just tried messing with the timezone as suggested above. The error persisted. Then I just decided to clear cookies from OpenSearch Dashboards / Kibana. The error went away. I can no longer reproduce it. Running a OpenSearch RC1 in docker with a minimal config.

```
Error
    at Fetch._callee3$ (https://[hostname]/36385/bundles/core/core.entry.js:6:59575)
    at tryCatch (https://[hostname]/36385/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:33172)
    at Generator.invoke [as _invoke] (https://[hostname]/36385/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:37136)
    at Generator.forEach.prototype.<computed> [as next] (https://[hostname]/36385/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:34297)
    at fetch_asyncGeneratorStep (https://[hostname]/36385/bundles/core/core.entry.js:6:52678)
    at _next (https://[hostname]/36385/bundles/core/core.entry.js:6:52994)
```

**Comment by vzhgit** [comment]
Maybe it's nor related but in a browser's console I saw the same error lines.
Firstly we had installed OpenSearch and OpenSearch Dashboard v1.0.0 in a k8s cluster and after a while we upgrade both of them to v 1.1.0.
And since that moment I had the same issue when I tried to open the Discover page in a Chrome browser on my computer with Windows.
Issue was fixed really easy.  
On Stack Managment\Advanced Settings page I reset "Timezone for date formatting" setting to default value and saved the page. The Discover page has started opening without errors, so I switched the setting to UTC back without any consciences.
