### ISSUE TITLE
[BUG] Parsing Issue

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/sql#1960]
Getting the following stack trace when running a "Describe Table" command in spark sql. I believe it has something to do with the comment column possibly being null as per example in spark-sql documentation: https://spark.apache.org/docs/3.0.0/sql-ref-syntax-aux-describe-table.html. Based on initial investigations it may be coming from this file: https://github.com/opensearch-project/sql/blob/main/spark/src/main/java/org/opensearch/sql/spark/functions/response/DefaultSparkSqlFunctionResponseHandle.java, but I am looking more into it.

org.json.JSONException: JSONObject["comment"] not found.
3|os-29  | 	at org.json.JSONObject.get(JSONObject.java:570) ~[json-20230227.jar:?]
3|os-29  | 	at org.json.JSONObject.getString(JSONObject.java:857) ~[json-20230227.jar:?]
3|os-29  | 	at org.opensearch.sql.spark.functions.response.DefaultSparkSqlFunctionResponseHandle.extractRow(DefaultSparkSqlFunctionResponseHandle.java:91) ~[spark-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.spark.functions.response.DefaultSparkSqlFunctionResponseHandle.constructIteratorAndSchema(DefaultSparkSqlFunctionResponseHandle.java:59) ~[spark-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.spark.functions.response.DefaultSparkSqlFunctionResponseHandle.<init>(DefaultSparkSqlFunctionResponseHandle.java:47) ~[spark-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.spark.functions.scan.SparkSqlFunctionTableScanOperator.lambda$open$0(SparkSqlFunctionTableScanOperator.java:41) ~[spark-2.9.0.0.jar:?]
3|os-29  | 	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
3|os-29  | 	at org.opensearch.sql.spark.functions.scan.SparkSqlFunctionTableScanOperator.open(SparkSqlFunctionTableScanOperator.java:37) ~[spark-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.opensearch.executor.protector.ResourceMonitorPlan.open(ResourceMonitorPlan.java:63) ~[opensearch-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.opensearch.executor.OpenSearchExecutionEngine.lambda$execute$0(OpenSearchExecutionEngine.java:48) [opensearch-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.opensearch.client.OpenSearchNodeClient.schedule(OpenSearchNodeClient.java:187) [opensearch-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.opensearch.executor.OpenSearchExecutionEngine.execute(OpenSearchExecutionEngine.java:42) [opensearch-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.executor.QueryService.lambda$executePlan$1(QueryService.java:66) [core-2.9.0.0.jar:?]
3|os-29  | 	at java.util.Optional.ifPresentOrElse(Optional.java:198) [?:?]
3|os-29  | 	at org.opensearch.sql.executor.QueryService.executePlan(QueryService.java:64) [core-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.executor.QueryService.execute(QueryService.java:43) [core-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.executor.execution.QueryPlan.execute(QueryPlan.java:71) [core-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.opensearch.executor.OpenSearchQueryManager.lambda$submit$0(OpenSearchQueryManager.java:33) [opensearch-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.sql.opensearch.executor.OpenSearchQueryManager.lambda$withCurrentContext$1(OpenSearchQueryManager.java:47) [opensearch-2.9.0.0.jar:?]
3|os-29  | 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:849) [opensearch-2.9.0.jar:2.9.0]
3|os-29  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
3|os-29  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
3|os-29  | 	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by dai-chen** [comment]
I think this is because the response is not JSON for some SQL statement, such as describe and explain. CC: @rupal-bq

**Comment by qianheng-aws** [comment]
Parking: Low activity and deprioritized during triage. Labeled `triage/parked` for tracking. Reopen if needed.
