### ISSUE TITLE
[BUG] Prometheus connector does not accept ips as host name

### ISSUE THREAD

**Issue by Spcemarine** [opensearch-project/sql#2106]
**What is the bug?**
The creation of a prometheus datasource will fail if you supply any ip as the hostname for the URI saying that the hostname is invalid.

**How can one reproduce the bug?**
Create a prometheus datasource with an ip as hostname in the uri property. E.g. 

```
POST _plugins/_query/_datasources 
  {
    "name": "my_prometheus",
    "connector": "prometheus",
    "properties": {
      "prometheus.uri": "http://172.25.0.3:9090"
    }
  }
```

**What is the expected behavior?**
The creation of prometheus datasources based on IPs is allowed.

**What is your host/environment?**
Running the latest docker image with a prometheus running on docker too, so ideally I wanted to use docker's dns but (something like `http://prometheus`) that was also denied by the hostname validation and then even plain ips did not work. :(

**Do you have any screenshots?**

No, but a stacktrace, even better right? 🤓

```
java.lang.IllegalArgumentException: Invalid hostname in the uri: http://172.25.0.3:9090
	at org.opensearch.sql.prometheus.storage.PrometheusStorageFactory.validateURI(PrometheusStorageFactory.java:154) ~[prometheus-2.9.0.0.jar:?]
	at org.opensearch.sql.prometheus.storage.PrometheusStorageFactory.validateDataSourceConfigProperties(PrometheusStorageFactory.java:80) ~[prometheus-2.9.0.0.jar:?]
	at org.opensearch.sql.prometheus.storage.PrometheusStorageFactory.lambda$getStorageEngine$0(PrometheusStorageFactory.java:88) ~[prometheus-2.9.0.0.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at org.opensearch.sql.prometheus.storage.PrometheusStorageFactory.getStorageEngine(PrometheusStorageFactory.java:86) ~[prometheus-2.9.0.0.jar:?]
	at org.opensearch.sql.prometheus.storage.PrometheusStorageFactory.createDataSource(PrometheusStorageFactory.java:61) ~[prometheus-2.9.0.0.jar:?]
	at org.opensearch.sql.datasources.service.DataSourceLoaderCacheImpl.getOrLoadDataSource(DataSourceLoaderCacheImpl.java:43) ~[datasources-2.9.0.0.jar:?]
	at org.opensearch.sql.datasources.service.DataSourceServiceImpl.createDataSource(DataSourceServiceImpl.java:100) ~[datasources-2.9.0.0.jar:?]
	at org.opensearch.sql.datasources.transport.TransportCreateDataSourceAction.doExecute(TransportCreateDataSourceAction.java:52) [datasources-2.9.0.0.jar:?]
	at org.opensearch.sql.datasources.transport.TransportCreateDataSourceAction.doExecute(TransportCreateDataSourceAction.java:23) [datasources-2.9.0.0.jar:?]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:218) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.indexmanagement.rollup.actionfilter.FieldCapsFilter.apply(FieldCapsFilter.kt:118) [opensearch-index-management-2.9.0.0.jar:2.9.0.0]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.indexmanagement.controlcenter.notification.filter.IndexOperationActionFilter.apply(IndexOperationActionFilter.kt:39) [opensearch-index-management-2.9.0.0.jar:2.9.0.0]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:78) [opensearch-performance-analyzer-2.9.0.0.jar:2.9.0.0]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:391) [opensearch-security-2.9.0.0.jar:2.9.0.0]
	at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:165) [opensearch-security-2.9.0.0.jar:2.9.0.0]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:188) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:107) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:476) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.sql.datasources.rest.RestDataSourceQueryAction.lambda$executePostRequest$1(RestDataSourceQueryAction.java:140) [datasources-2.9.0.0.jar:?]
	at org.opensearch.sql.datasources.utils.Scheduler.lambda$withCurrentContext$0(Scheduler.java:30) [datasources-2.9.0.0.jar:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:849) [opensearch-2.9.0.jar:2.9.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

Would be nice to be able to use docker's dns feature directly since I actually did not want to use ips but I'm not sure if that's a feature request or bug report. If it's the former I can open a new issue for that. Also, I do not quite understand why it is required to do exessive domain validation and would challenge that entirely but I might be missing the bigger picture here.

**Comment by dai-chen** [comment]
@vamsi-amazon any idea?

**Comment by vamsi-amazon** [comment]
Thanks for the issue. This is due to the validation on the host provided here: https://github.com/opensearch-project/sql/blob/61d1eb7d6bab3bed88adbe9c40f027cea52f5c94/datasources/src/main/java/org/opensearch/sql/datasources/utils/DatasourceValidationUtils.java#L62

We could get away with the above code as we really don't need to validate the domain for SSRF issue.

**Comment by yoicomment** [comment]
Currently it is also not possible to pass prometheus uri's with ".local" or ".lan" and many more TLDs. Would your PR solve that also? And can we expect that this fix is available in OS 2.10?

**Comment by Habib-Mergan** [comment]
When will this fix be available?

**Comment by yoicomment** [comment]
Or is it already available after merging? How does that work?

**Comment by yoicomment** [comment]
@Spcemarine does it work now?
