### ISSUE TITLE
[BUG] DESC SKIPPING IINDEX NPE

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql#2356]
### Customized UT, failed.
```
  @Test
  void testDescSkippingIndex() {
    String descSkippingIndex = "DESC SKIPPING INDEX ON mys3.default.http_logs";
    Assertions.assertTrue(SQLQueryUtils.isIndexQuery(descSkippingIndex));
    IndexDetails indexDetails = SQLQueryUtils.extractIndexDetails(descSkippingIndex);
    FullyQualifiedTableName fullyQualifiedTableName = indexDetails.getFullyQualifiedTableName();
    Assertions.assertNull(indexDetails.getIndexName());
    Assertions.assertNull(fullyQualifiedTableName);
    Assertions.assertEquals(SKIPPING, indexDetails.getIndexType());
  }

Index Type can't be null
java.lang.NullPointerException: Index Type can't be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:921)
	at org.opensearch.sql.spark.dispatcher.model.IndexDetails$IndexDetailsBuilder.build(IndexDetails.java:76)
```

**Comment by penghuo** [comment]
close by. https://github.com/opensearch-project/sql/pull/2357
