### ISSUE TITLE
[BUG] Fix DateTimeFunctionTest. testWeekOfYearWithTimeType() YearweekTest. testYearweekWithTimeType() Unit tests.

### ISSUE THREAD

**Issue by vamsimanohar** [opensearch-project/sql#2477]
**What is the bug?**

* ```DateTimeFunctionTest. testWeekOfYearWithTimeType() YearweekTest. testYearweekWithTimeType()``` unit tests are temporarily fixed in this PR here : https://github.com/opensearch-project/sql/pull/2476. 
* The ask from this bug is to come up with a proper fix for it.

Issue details: Jan 2024 starts with Monday and we calculate weekoftheyear using SUNDAY as the firstdayoftheweek this makes 22nd Jan 3rd week of the year rather 4th week. 

We can consider moving to LocalDateTime instead of Calendar.

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by kenrickyap** [comment]
am currently looking these test failures

**Comment by acarbonetto** [comment]
Reopened due to current CI test failures: https://github.com/opensearch-project/sql/actions/runs/13124882810/job/36619055365

```
ExtractTest > testExtractDatePartWithTimeType() FAILED
    org.opentest4j.AssertionFailedError: expected: <5> but was: <6>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:635)
        at app//org.opensearch.sql.expression.datetime.ExtractTest.datePartWithTimeArgQuery(ExtractTest.java:90)
        at app//org.opensearch.sql.expression.datetime.ExtractTest.testExtractDatePartWithTimeType(ExtractTest.java:106)
```
