### ISSUE TITLE
[BUG] Cannot fetch metrics list from prometheus

### ISSUE THREAD

**Issue by vladislav1q** [opensearch-project/sql#3197]
**What is the bug?**
I created new data source from prometheus. The status is active. The error occurs when i go into it when processing PPL.

**What is the expected behavior?**

**What is your host/environment?**
 - Opensearch 2.16.0+ in container on debian/ubuntu

![image](https://github.com/user-attachments/assets/d131e7c6-b1a7-4845-a997-747ba5c26377)

Maybe i made incorrect configuration. I tried many options, that did not work. Seems that a detailed guide with configurations for the new prometheus data source required.

**Comment by vmmusings** [comment]
Hi @vladislav1q  prometheus datasource feature is still in early experimental phase, can you post more details on what exact query are you trying and how did you set up the datasource?

**Comment by DevOpsWithG** [comment]
Dear @vamsimanohar,
I'm also facing somewhat the same issue. Could you please help me with this error.
I have deployed Opensearch and Opensearch dashboard with latest version of 2.19.1, everything is up and running.
Opensearch dashboard is accessible at https://a6.abc.com/opensearch and proemtheus is accessible at https://a6.abc.com/prometheus

I added data source using dev tools 
```
POST _plugins/_query/_datasources 
{
    "name" : "my_prometheus",
    "connector": "prometheus",
    "properties" : {
        "prometheus.uri" : "https://a6.abc.com/prometheus"
    }
}
```

But when i add data source and try to query, I don't see any metric and gets below logs in opensearch and opensearch dashboard pod.
```
'{\n' +
    '  "error": {\n' +
    '    "reason": "There was internal problem at backend",\n' +
    '    "details": "Error while fetching metric list for from prometheus: Failed to parse server certificates",\n' +
    '    "type": "RuntimeException"\n' +
    '  },\n' +
    '  "status": 500\n' +
    '}',
  statusCode: 500,
  response: '{\n' +
    '  "error": {\n' +
    '    "reason": "There was internal problem at backend",\n' +
    '    "details": "Error while fetching metric list for from prometheus: Failed to parse server certificates",\n' +
    '    "type": "RuntimeException"\n' +
    '  },\n' +
    '  "status": 500\n' +
    '}',
  toString: [Function (anonymous)],
  toJSON: [Function (anonymous)]
}

{"type":"error","@timestamp":"2025-03-21T05:46:09Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:127:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:83:19)\n    at HapiResponseAdapter.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:79:17)\n    at Router.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:175:34)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at handler (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:140:50)\n    at exports.Manager.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:281:9)"},"url":"http://a6.abc.com/api/ppl/search?dataSourceMDSId=","message":"Internal Server Error"}
```

**Comment by qianheng-aws** [comment]
Parking: Low activity and deprioritized during triage. Labeled `triage/parked` for tracking. Reopen if needed.
