### ISSUE TITLE
[BUG] Some Queries generated by Tableau aren't runnable when OpenSearch is data source

### ISSUE THREAD

**Issue by domzim** [opensearch-project/sql#885]
**What is the bug?**
When OpenSearch is used as a data source for Tableau, some queries that Tableau generates aren't runnable in OpenSearch.

**How can one reproduce the bug?**
1. Use filter in Tableau on column with values A,B,C,D,E,F and Z
2. Select less then half of the possible values (A,B,C)
Generated query looks like this:
SELECT COUNT(`ekr`.`rks`) AS `cnt_rks`,
     `ekr`.`crp` AS `cr`,
     `ekr`.`p` AS `p`
   FROM `ekr`
   WHERE (`ekr`.`p` IN ('A', 'B', 'C')) GROUP BY `crp`, `p`

-> Everything works

3. Select more then half of the values (A,B,C,D,E,F) 
Generated query looks like this:
SELECT COUNT(`ekr`.`rks`) AS `cnt_rks`,
	 `ekr`.`crp` AS `crp`,
	 `ekr`.`p` AS `p` 
	FROM `ekr` 
	WHERE (CASE WHEN ((`ekr`.`p` IN ('Z')) OR ISNULL(`ekr`.`p`)) THEN 0 ELSE 1 END) GROUP BY `crp`, `p`

-> Doesn't work and trying the same query in Query Workbench results in "Bad Request, this query is not runnable."

**What is the expected behavior?**
Query should probably work since it's correct sql syntax?

**What is your host/environment?**
 - OS: Windows
 - OpenSearch 2.3.0
 - Tableau Desktop 2022.2
 - JDBC Driver + Tableau Connector

**Comment by Yury-Fridlyand** [comment]
I discovered that nesting `IN` into `CASE` clause causes the crash:
```sql
select `key` from calcs where (CASE WHEN (1 IN (1)) THEN 0 ELSE 1 END);
```
error returned:
```
TransportError(500, 'SearchPhaseExecutionException', {'error': {'type': 'SearchPhaseExecutionException', 'reason': 'Error occurred in OpenSearch engine: all shards failed', 'details': 'Shard[0]: java.lang.IllegalStateException: Expression has wrong result type instead of boolean: expression [CaseClause(whenClauses=[WhenClause(condition==(1, 1), result=0)], defaultResult=1)], result [0]\n\nFor more details, please send request for Json format to see the raw response from OpenSearch engine.'}, 'status': 503})
```
exception stack:
```
Error happened during query handling
org.opensearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:661) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:371) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:696) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:469) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:293) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:74) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:615) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TransportService$6.handleException(TransportService.java:759) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1379) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1493) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1467) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:79) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:71) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:70) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:103) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:54) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opensearch.OpenSearchException$1: Expression has wrong result type instead of boolean: expression [CaseClause(whenClauses=[WhenClause(condition==(1, 1), result=0)], defaultResult=1)], result [0]
        at org.opensearch.OpenSearchException.guessRootCauses(OpenSearchException.java:683) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:369) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        ... 23 more
Caused by: java.lang.IllegalStateException: Expression has wrong result type instead of boolean: expression [CaseClause(whenClauses=[WhenClause(condition==(1, 1), result=0)], defaultResult=1)], result [0]
        at org.opensearch.sql.opensearch.storage.script.filter.ExpressionFilterScript.evaluateExpression(ExpressionFilterScript.java:54) ~[?:?]
        at org.opensearch.sql.opensearch.storage.script.core.ExpressionScript.lambda$execute$2(ExpressionScript.java:83) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.opensearch.sql.opensearch.storage.script.core.ExpressionScript.execute(ExpressionScript.java:80) ~[?:?]
        at org.opensearch.sql.opensearch.storage.script.filter.ExpressionFilterScript.execute(ExpressionFilterScript.java:43) ~[?:?]
        at org.opensearch.index.query.ScriptQueryBuilder$ScriptQuery$1$1.matches(ScriptQueryBuilder.java:226) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:281) ~[lucene-core-9.3.0.jar:9.3.0 d25cebcef7a80369f4dfb9285ca7360a810b75dc - ivera - 2022-07-25 12:30:23]
        at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:254) ~[lucene-core-9.3.0.jar:9.3.0 d25cebcef7a80369f4dfb9285ca7360a810b75dc - ivera - 2022-07-25 12:30:23]
        at org.opensearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:71) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38) ~[lucene-core-9.3.0.jar:9.3.0 d25cebcef7a80369f4dfb9285ca7360a810b75dc - ivera - 2022-07-25 12:30:23]
        at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:279) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:250) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:514) ~[lucene-core-9.3.0.jar:9.3.0 d25cebcef7a80369f4dfb9285ca7360a810b75dc - ivera - 2022-07-25 12:30:23]
        at org.opensearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:349) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWithCollector(QueryPhase.java:443) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWith(QueryPhase.java:432) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:275) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:152) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:450) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:514) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:483) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        ... 8 more
[2022-10-04T21:21:16,040][ERROR][o.o.s.l.p.RestSQLQueryAction] [Yury-ThinkPad] Server side error during query execution
org.opensearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:661) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:371) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:696) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:469) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:293) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:74) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:615) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TransportService$6.handleException(TransportService.java:759) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1379) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1493) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1467) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:79) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:71) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:70) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:103) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:54) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:806) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opensearch.OpenSearchException$1: Expression has wrong result type instead of boolean: expression [CaseClause(whenClauses=[WhenClause(condition==(1, 1), result=0)], defaultResult=1)], result [0]
        at org.opensearch.OpenSearchException.guessRootCauses(OpenSearchException.java:683) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:369) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        ... 23 more
Caused by: java.lang.IllegalStateException: Expression has wrong result type instead of boolean: expression [CaseClause(whenClauses=[WhenClause(condition==(1, 1), result=0)], defaultResult=1)], result [0]
        at org.opensearch.sql.opensearch.storage.script.filter.ExpressionFilterScript.evaluateExpression(ExpressionFilterScript.java:54) ~[?:?]
        at org.opensearch.sql.opensearch.storage.script.core.ExpressionScript.lambda$execute$2(ExpressionScript.java:83) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.opensearch.sql.opensearch.storage.script.core.ExpressionScript.execute(ExpressionScript.java:80) ~[?:?]
        at org.opensearch.sql.opensearch.storage.script.filter.ExpressionFilterScript.execute(ExpressionFilterScript.java:43) ~[?:?]
        at org.opensearch.index.query.ScriptQueryBuilder$ScriptQuery$1$1.matches(ScriptQueryBuilder.java:226) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:281) ~[lucene-core-9.3.0.jar:9.3.0 d25cebcef7a80369f4dfb9285ca7360a810b75dc - ivera - 2022-07-25 12:30:23]
        at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:254) ~[lucene-core-9.3.0.jar:9.3.0 d25cebcef7a80369f4dfb9285ca7360a810b75dc - ivera - 2022-07-25 12:30:23]
        at org.opensearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:71) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38) ~[lucene-core-9.3.0.jar:9.3.0 d25cebcef7a80369f4dfb9285ca7360a810b75dc - ivera - 2022-07-25 12:30:23]
        at org.opensearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:279) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:250) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:514) ~[lucene-core-9.3.0.jar:9.3.0 d25cebcef7a80369f4dfb9285ca7360a810b75dc - ivera - 2022-07-25 12:30:23]
        at org.opensearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:349) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWithCollector(QueryPhase.java:443) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher.searchWith(QueryPhase.java:432) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.query.QueryPhase.executeInternal(QueryPhase.java:275) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:152) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:450) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:514) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:483) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        ... 8 more
```

**Comment by domzim** [comment]
Thank you for looking into this! Is this something which can/will be fixed in the foreseeable future?

**Comment by dai-chen** [comment]
@domzim Thanks for reporting the issue! I think the root cause is as indicated in error message "Expression has wrong result type instead of boolean". To use case statement in WHERE, it has to be changed to predicate like `CASE WHEN (1 IN (1)) THEN TRUE ELSE FALSE END` or `(CASE WHEN (1 IN (1)) THEN 0 ELSE 1 END) = 0`.

From our side, I'm not sure if we should support implicit conversion from 0/1 to boolean. But something we may improve is throw semantic exception in analyzer instead of raising error at execution time. Thanks!

**Comment by domzim** [comment]
@dai-chen Thank you for the response and I understand your concerns. I just have to switch to another solution for my problem then. 
Can be closed if it's not needed anymore!

**Comment by MaxKsyunz** [comment]
Let's keep it open. We may not fix it at OpenSearch level, but maybe in the connector.
